# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(520, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 690))
        MainWindow.setMaximumSize(QtCore.QSize(520, 690))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(41, 41, 53);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(131, 186, 182);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(69, 167, 123);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 500, 646))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_calculate = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_calculate.sizePolicy().hasHeightForWidth())
        self.button_calculate.setSizePolicy(sizePolicy)
        self.button_calculate.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_calculate.setFont(font)
        self.button_calculate.setAutoFillBackground(False)
        self.button_calculate.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 15;\n"
"border: 3px solid rgb(56, 108, 161);\n"
"\n"
"")
        self.button_calculate.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.button_calculate.setObjectName("button_calculate")
        self.gridLayout.addWidget(self.button_calculate, 10, 0, 1, 3)
        self.date_sale_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_sale_label.sizePolicy().hasHeightForWidth())
        self.date_sale_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.date_sale_label.setFont(font)
        self.date_sale_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.date_sale_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_sale_label.setObjectName("date_sale_label")
        self.gridLayout.addWidget(self.date_sale_label, 8, 0, 1, 1)
        self.date_buy_dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.date_buy_dateEdit.setFont(font)
        self.date_buy_dateEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.date_buy_dateEdit.setObjectName("date_buy_dateEdit")
        self.gridLayout.addWidget(self.date_buy_dateEdit, 6, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(139, 141, 181);\n"
"color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.purchase_price_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.purchase_price_lineedit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.purchase_price_lineedit.setFont(font)
        self.purchase_price_lineedit.setTabletTracking(False)
        self.purchase_price_lineedit.setToolTipDuration(-1)
        self.purchase_price_lineedit.setAutoFillBackground(False)
        self.purchase_price_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);")
        self.purchase_price_lineedit.setMaxLength(100)
        self.purchase_price_lineedit.setFrame(True)
        self.purchase_price_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.purchase_price_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.purchase_price_lineedit.setObjectName("purchase_price_lineedit")
        self.gridLayout.addWidget(self.purchase_price_lineedit, 5, 2, 1, 1)
        self.date_sale_dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.date_sale_dateEdit.setFont(font)
        self.date_sale_dateEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.date_sale_dateEdit.setObjectName("date_sale_dateEdit")
        self.gridLayout.addWidget(self.date_sale_dateEdit, 8, 2, 1, 1)
        self.date_maturity_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_maturity_label.sizePolicy().hasHeightForWidth())
        self.date_maturity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.date_maturity_label.setFont(font)
        self.date_maturity_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.date_maturity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_maturity_label.setObjectName("date_maturity_label")
        self.gridLayout.addWidget(self.date_maturity_label, 7, 0, 1, 1)
        self.purchase_price_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.purchase_price_label.sizePolicy().hasHeightForWidth())
        self.purchase_price_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.purchase_price_label.setFont(font)
        self.purchase_price_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.purchase_price_label.setAlignment(QtCore.Qt.AlignCenter)
        self.purchase_price_label.setObjectName("purchase_price_label")
        self.gridLayout.addWidget(self.purchase_price_label, 5, 0, 1, 1)
        self.date_maturity_dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.date_maturity_dateEdit.setFont(font)
        self.date_maturity_dateEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(255, 255, 255);")
        self.date_maturity_dateEdit.setObjectName("date_maturity_dateEdit")
        self.gridLayout.addWidget(self.date_maturity_dateEdit, 7, 2, 1, 1)
        self.nominal_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nominal_label.sizePolicy().hasHeightForWidth())
        self.nominal_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.nominal_label.setFont(font)
        self.nominal_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.nominal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nominal_label.setObjectName("nominal_label")
        self.gridLayout.addWidget(self.nominal_label, 1, 0, 1, 1)
        self.ACI_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ACI_lineedit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ACI_lineedit.setFont(font)
        self.ACI_lineedit.setTabletTracking(False)
        self.ACI_lineedit.setToolTipDuration(-1)
        self.ACI_lineedit.setAutoFillBackground(False)
        self.ACI_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);")
        self.ACI_lineedit.setMaxLength(100)
        self.ACI_lineedit.setFrame(True)
        self.ACI_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ACI_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ACI_lineedit.setObjectName("ACI_lineedit")
        self.gridLayout.addWidget(self.ACI_lineedit, 2, 2, 1, 1)
        self.value_coupon_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.value_coupon_lineedit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.value_coupon_lineedit.setFont(font)
        self.value_coupon_lineedit.setTabletTracking(False)
        self.value_coupon_lineedit.setToolTipDuration(-1)
        self.value_coupon_lineedit.setAutoFillBackground(False)
        self.value_coupon_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);")
        self.value_coupon_lineedit.setMaxLength(100)
        self.value_coupon_lineedit.setFrame(True)
        self.value_coupon_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.value_coupon_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.value_coupon_lineedit.setObjectName("value_coupon_lineedit")
        self.gridLayout.addWidget(self.value_coupon_lineedit, 3, 2, 1, 1)
        self.date_buy_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_buy_label.sizePolicy().hasHeightForWidth())
        self.date_buy_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.date_buy_label.setFont(font)
        self.date_buy_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.date_buy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_buy_label.setObjectName("date_buy_label")
        self.gridLayout.addWidget(self.date_buy_label, 6, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setIconSize(QtCore.QSize(32, 32))
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 9, 0, 1, 2)
        self.nominal_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nominal_lineedit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.nominal_lineedit.setFont(font)
        self.nominal_lineedit.setTabletTracking(False)
        self.nominal_lineedit.setToolTipDuration(-1)
        self.nominal_lineedit.setAutoFillBackground(False)
        self.nominal_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);")
        self.nominal_lineedit.setMaxLength(100)
        self.nominal_lineedit.setFrame(True)
        self.nominal_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.nominal_lineedit.setCursorPosition(0)
        self.nominal_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nominal_lineedit.setObjectName("nominal_lineedit")
        self.gridLayout.addWidget(self.nominal_lineedit, 1, 2, 1, 1)
        self.yield_to_maturity_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.yield_to_maturity_lineedit.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(17)
        self.yield_to_maturity_lineedit.setFont(font)
        self.yield_to_maturity_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 171, 139);\n"
"border: 2px solid rgb(181, 75, 106);\n"
"border-radius: 30;\n"
"")
        self.yield_to_maturity_lineedit.setAlignment(QtCore.Qt.AlignCenter)
        self.yield_to_maturity_lineedit.setReadOnly(True)
        self.yield_to_maturity_lineedit.setObjectName("yield_to_maturity_lineedit")
        self.gridLayout.addWidget(self.yield_to_maturity_lineedit, 11, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30;\n"
"border: 2px solid rgb(181, 75, 106)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 11, 0, 1, 1)
        self.ACI_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ACI_label.sizePolicy().hasHeightForWidth())
        self.ACI_label.setSizePolicy(sizePolicy)
        self.ACI_label.setMinimumSize(QtCore.QSize(321, 0))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ACI_label.setFont(font)
        self.ACI_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.ACI_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACI_label.setObjectName("ACI_label")
        self.gridLayout.addWidget(self.ACI_label, 2, 0, 1, 1)
        self.value_coupon_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_coupon_label.sizePolicy().hasHeightForWidth())
        self.value_coupon_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.value_coupon_label.setFont(font)
        self.value_coupon_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.value_coupon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.value_coupon_label.setObjectName("value_coupon_label")
        self.gridLayout.addWidget(self.value_coupon_label, 3, 0, 1, 1)
        self.coupon_period_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coupon_period_label.sizePolicy().hasHeightForWidth())
        self.coupon_period_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.coupon_period_label.setFont(font)
        self.coupon_period_label.setStyleSheet("background-color: rgb(69, 71, 92);\n"
"color: white;\n"
"border-radius: 10;\n"
"border: 2px solid rgb(56, 108, 161)")
        self.coupon_period_label.setAlignment(QtCore.Qt.AlignCenter)
        self.coupon_period_label.setObjectName("coupon_period_label")
        self.gridLayout.addWidget(self.coupon_period_label, 4, 0, 1, 1)
        self.coupon_period_lineedit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.coupon_period_lineedit.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.coupon_period_lineedit.setFont(font)
        self.coupon_period_lineedit.setTabletTracking(False)
        self.coupon_period_lineedit.setToolTipDuration(-1)
        self.coupon_period_lineedit.setAutoFillBackground(False)
        self.coupon_period_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(255, 255, 255);")
        self.coupon_period_lineedit.setMaxLength(100)
        self.coupon_period_lineedit.setFrame(True)
        self.coupon_period_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.coupon_period_lineedit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.coupon_period_lineedit.setObjectName("coupon_period_lineedit")
        self.gridLayout.addWidget(self.coupon_period_lineedit, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculation of bond yields"))
        self.button_calculate.setText(_translate("MainWindow", "Calculation"))
        self.date_sale_label.setText(_translate("MainWindow", "The date of sale (If there is)"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ENG"))
        self.comboBox.setItemText(1, _translate("MainWindow", "RU"))
        self.date_maturity_label.setText(_translate("MainWindow", "The date of maturity"))
        self.purchase_price_label.setText(_translate("MainWindow", "The purchase price\n"
"(percentage of the nominal)"))
        self.nominal_label.setText(_translate("MainWindow", "The nominal of bond"))
        self.date_buy_label.setText(_translate("MainWindow", "The date of buy"))
        self.checkBox.setText(_translate("MainWindow", "Calculation including tax"))
        self.yield_to_maturity_lineedit.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Yield to maturity\n"
"(Annual interest)"))
        self.ACI_label.setText(_translate("MainWindow", "Accumulated coupon income"))
        self.value_coupon_label.setText(_translate("MainWindow", "The coupon value"))
        self.coupon_period_label.setText(_translate("MainWindow", "Сoupon period in days"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
